version: '3'
services:
  app:
    #image: ferwguerra/hello-world
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/users?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    #image: ferwguerra/my_mysql
    build:
      context: .
      dockerfile: Dockerfile_db
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: